### ISSUE TITLE
Document TEAM_NAME_BLACKLIST

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-teams#11]

**Comment by arthur-wsw** [comment]
TEAM_NAME_BLACKLIST must be added in settings for app to works it should definitively be on docs.

**Comment by jacobwegner** [comment]
#39 renames this setting to `TEAMS_NAME_BLACKLIST` for consistency with the other settings.

This setting should also be added to the template for the [team-wiki starter project](https://github.com/pinax/pinax-starter-projects/blob/3c2eb174a762e2d0aeb3ede30b84211353231925/project_name/settings.py)

**Comment by grahamu** [comment]
The setting is now `PINAX_TEAMS_NAME_BLACKLIST` to match other Pinax app settings, and is included by default in conf.py.
