### ISSUE TITLE
Minimum required version for django-reversion should be 1.10

### ISSUE THREAD

**Issue by john2x** [pinax/pinax-teams#33]
The `reversion.revisions.register` function was introduced in 1.10.

1.9.3 https://github.com/etianen/django-reversion/blob/release-1.9.3/src/reversion/revisions.py#L643
1.10.0 https://github.com/etianen/django-reversion/blob/release-1.10.0/src/reversion/revisions.py#L639

**Comment by grahamu** [comment]
Requirement updated to django-reversion=>2.0.12.
