### ISSUE TITLE
Templates use two differents folders

### ISSUE THREAD

**Issue by arthur-wsw** [pinax/pinax-teams#34]
Currently when you use this app, you need to add two templates folders, one in templates/teams and one in templates/pinax_teams.

I think templates for one app should be referenced in only one folder.
If i look in others pinax apps, i think it should be in templates/pinax/teams.

**Comment by grahamu** [comment]
Thanks for bringing this to our attention @arthur-wsw. As you suggested the templates are now expected to be found in "pinax/teams/" in your project in the template path.

See https://github.com/pinax/pinax-teams/pull/58.
