### ISSUE TITLE
Membership fields not migrated to delete CASCADE

### ISSUE THREAD

**Issue by ludovicthomas** [pinax/pinax-teams#60]
First thanks a lot for the great Pinax projects. Quite helpful to quick start a project.

I just used the Pinax-teams 1.0.1, and when running `manage.py makemigrations` on my own project, it created a file `0005_auto_20180122_0941.py` at `/usr/local/lib/python3.6/site-packages/pinax/teams/migrations/`.

The content is

```
migrations.AlterField(
            model_name='membership',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pinax_invitations.JoinInvitation', verbose_name='invite'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='simplemembership',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_memberships', to='pinax_invitations.JoinInvitation', verbose_name='invite'),
        ),
        migrations.AlterField(
            model_name='simplemembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
```

And if I check the history of migrations it was previously not a CASCADE to NULL
As in `0001_initial.py`:
```
('invite', models.ForeignKey(related_name='memberships', verbose_name='invite', blank=True, to='pinax_invitations.JoinInvitation', null=True, on_delete=models.SET_NULL))
```

Is it possible to create a new migration and publish a new version on PyPI?
Am I missing something?

**Comment by grahamu** [comment]
@ludovicthomas you are not missing anything, thanks for bringing this to our attention. I have a feeling CASCADE was a mistake on my part.

**Comment by grahamu** [comment]
@ludovicthomas the model field `on_delete` problem has been fixed. "CASCADE" has been reverted to "SET_NULL", and no new migration is needed.

Please use the latest PyPi release, v1.0.2. https://pypi.python.org/pypi/pinax-teams/1.0.2

Thanks again for your bug report!

**Comment by ludovicthomas** [comment]
It works. Thanks. Can be closed.
