### ISSUE TITLE
Running without Pinax dependencies?

### ISSUE THREAD

**Issue by lggwettmann** [pinax/pinax-teams#64]
Hey guys, 

I'd love to use pinax-teams, but my app is not built with pinax-user-accounts or any of the other apps. I am willing to add some dependencies, but as I already use django-allauth and my app user authentication is handled, I'd rather not add pinax-user-accounts.

Is there a way to use pinax-teams without all the dependencies or at least pinax-user-accounts? Alternatively, do you know about similar packages? I couldn't find anything useful. Thanks for your help in advance.

**Comment by KatherineMichel** [comment]
Pinax Teams is open source with an MIT license. You are free to modify it however you see fit. But Pinax Teams and DUA are integrated together, so might not be worth your time to re-configure. I'm not sure about a replacement. If you post in our Slack help channel, someone else might have an idea. Or you could search GitHub or PyPi. I'm sure there are alternatives. http://slack.pinaxproject.com/

**Comment by jtauber** [comment]
I presume you're fine with using `pinax-invitations` so the only issue is `django-user-accounts`?

It may be possible to remove that dependency.

**Comment by jtauber** [comment]
Ironically, django-allauth started off from django-user-accounts so much of this sort of thing could have been avoided if they'd just collaborated from the start rather than forked the code :-)

**Comment by jacobwegner** [comment]
@lggwettmann I agree that there'd be a fair amount of work to abstract the `django-user-accounts` and `pinax-invitations` dependencies out to swappable backends for other registration / invitation apps.

An alternative project with similar functionality to this project is [django-organizations](https://github.com/bennylope/django-organizations).  I can't speak as to how well it might integrate with `django-allauth`, but I think it is worth a closer look:

http://django-organizations.readthedocs.io/en/latest/usage.html#invitation-registration-backends

**Comment by lggwettmann** [comment]
Thanks, guys. I'll check out django-organizations first, before I look into modifying django-teams.

I see the advantages of the pinax suite, but prefer the loose coupling over pinax's 'lock-in' to its dependency apps. So I'm quite happy with all-auth on itself tbh. And a DUA with a fallback seems like an ideal solution to me. Kind of best of both worlds: great coupling with the pinax apps if available, but still usable for everyone else.

**Comment by KatherineMichel** [comment]
Closing issue as resolved.
