### ISSUE TITLE
pinax_teams:dashboard

### ISSUE THREAD

**Issue by xmnlab** [pinax/pinax-teams#65]
hi everyone!

We are trying to use the pinax-teams project. It is very interesting. 

Now we have a problem related to pinax_teams:dashboard -> https://github.com/pinax/pinax-teams/blob/master/pinax/teams/views.py#L162

where it is defined?

cc @utabe

**Comment by KatherineMichel** [comment]
@xmnlab Hello, are you using the pinax team wiki starter project or pinax-team just as an app? Within the starter project, there is a dashboard template. I think within that particular view, the dashboard template can be rendered via the ```team_leave``` url that I've linked to.
https://github.com/pinax/pinax-teams/blob/master/pinax/teams/urls.py#L16
https://github.com/pinax/pinax-starter-projects/tree/team-wiki/project_name/templates

**Comment by xmnlab** [comment]
thanks @KatherineMichel !

we are using the pinax-team just as an app but we copied the template files from pinax-team-wiki-project.

we will investigate the references you sent. thank you so much!

**Comment by KatherineMichel** [comment]
Great. Let me know if you need more assistance. I will try to help. There is also a pinax-templates package that is installed into starter-projects. However, many of the admin templates are within the projects themselves.

**Comment by KatherineMichel** [comment]
Closing issues because appears to be resolved.
