### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by uhurusurfa** [pinax/pinax-teams#70]
Is there an intention to support Django 4 in ths project in the near future?

**Comment by uhurusurfa** [comment]
@grahamu @KatherineMichel  - is there any intention to continue maintaining and upgrading the Pinax apps bu the existing projects admins?
If not, are you willing to add other admins willing to do the work?

**Comment by uhurusurfa** [comment]
Bump @grahamu @KatherineMichel

**Comment by uhurusurfa** [comment]
@brosner @paltman @jtauber @rizumu  - is there anyone that can respond to the above?

**Comment by paltman** [comment]
I think we'd be happy for other maintainers to join. We haven't really established a process for that but I think we could if there is an interest.

**Comment by uhurusurfa** [comment]
Excellent - thanks. Would you be able to add me (uhurusurfa) and martin-marty user IDs to the **pinax-teams** repo so we can raise PR's and merge fixes to get it up to Django 4 compatibility?

**Comment by KatherineMichel** [comment]
Sorry for the late reply. Just now saw this. I'd love to work together with you all to get up to Django 4 compatibility.

**Comment by uhurusurfa** [comment]
Any help would be appreciated either to add me to the team or for someone to d othe work to support Django 4

**Comment by paltman** [comment]
@uhurusurfa Happy to add you as a maintainer if you'd like.  I can add you here to this repo and to PyPI so you can make releases.  Just need to know your PyPI username.

**Comment by uhurusurfa** [comment]
@paltman - thank you. Username on PyPi is uhurusurfa
