### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-teams#9]
both `pinax.teams` and `kaleo` must be present in `INSTALLED_APPS`, or migrations will fail.

**Comment by jacobwegner** [comment]
`reversion` is also required to use the `teams` admin.

**Comment by grahamu** [comment]
I believe this is handled in the latest release. `django-reversion` is in setup.py installation requirements, as well as `pinax-invitations` (nee `kaleo`).
